# Generated by Django 5.2.3 on 2025-06-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lessoncontent_codetask_quiz_quizquestion_quizoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Длительность в минутах'),
        ),
    ]
